#!/usr/bin/env ruby

require 'json'
require 'open-uri'
require 'redditkit'

require './support/redditkit_extensions.rb'

require './lib/configuration.rb'
require './lib/player_names.rb'
require './lib/primary_listener.rb'
require './lib/subreddits.rb'
require './lib/tasks/schedule.rb'
require './lib/tasks/standings.rb'
require './lib/teams.rb'

client = RedditKit::Client.new 
client.user_agent = "Burnie (/r/Heat) 1.0"
client.sign_in Configuration["username"], Configuration["password"]

if client.signed_in?
  begin
    case ARGV[0]
    when "schedule"
      task = ScheduleTask.new
      year, month, day = Time.now.year, Time.now.month, Time.now.day
      month = 10 if month < 10 && year < 2015
      task.call(client, year, month, day)
    when "standings"
      task = StandingsTask.new
      task.call(client)
    else
      PrimaryListener.listen(client)
    end
  ensure
    client.sign_out
  end
else
  puts "Failed auth :("
end
